# Generated by Django 4.0.6 on 2022-10-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_email_alter_user_kakao_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
